name: Add Blowfish Submodule

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add-submodule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add Blowfish submodule
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git submodule add https://github.com/nunocoracao/blowfish.git themes/blowfish
          git commit -m "Add Blowfish as submodule"
          git push
